language: cpp
os: linux

jobs:
  include:
    - name: Ubuntu Xenial 16.04 with g++-7
      os: linux
      dist: xenial
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: CONFIGURE_ARGS="CC=gcc-7 CXX=g++-7"
    - name: Ubuntu Bionic 18.04
      os: linux
      dist: bionic
      env:
    - name: macOS Xcode11.3
      os: osx
      osx_image: xcode11.3

script:
  - touch aclocal.m4 configure Makefile.am Makefile.in
  - eval "./configure ${CONFIGURE_ARGS}"
  - make -j8
  - make check || { cat 'test/test-suite.log' && exit 1; }

git:
  depth: 1
