# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Prepare system
          command: |
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get -qq update
            sudo apt-get -qy install g++-7 automake autoconf-archive
      - run:
          name: Build
          command: |
            touch aclocal.m4 configure Makefile.am Makefile.in
            ./configure CXX=g++-7
            make -j8
            make check || { cat 'test/test-suite.log' && exit 1; }
